In [1]:
import pandas as pd

df = pd.read_csv( 'filmes_tmdb_veloz.csv', sep = ',' )

df

,title,release_date,vote_average,budget,vote_count,revenue,runtime,production_country,genres,release_year
0,Doctor X,1950-09-21,0.000,0,0,0,0,Philippines,"Comédia, Mistério, Terror",1950
1,Missão nos Balcãs,1950-12-06,6.000,0,12,0,90,United Kingdom,"Thriller, Ação",1950
2,Sarumba,1950-01-31,6.000,0,1,0,65,United States of America,"Drama, Música",1950
3,No Trace,1950-09-08,6.800,0,5,0,76,United Kingdom,"Crime, Drama",1950
4,Teatro Apolo,1950-10-30,6.300,0,7,0,105,NaN,Drama,1950
...,...,...,...,...,...,...,...,...,...,...
75990,BLUNT,2025-09-06,0.000,6500,0,0,13,Australia,"Drama, Família, Comédia",2025
75991,Light Bunny,2025-08-01,10.000,0,1,0,15,NaN,Drama,2025
75992,Curse of Crom 2: Crom's Fury,2025-09-20,0.000,0,0,0,0,United States of America,"Fantasia, Terror",2025
75993,Memórias de um Verão,2025-01-31,7.115,5000000,26,0,90,"Finland, United Kingdom, United States of America",Drama,2025
75994,Nix ist fix,2025-07-01,0.000,0,0,0,88,Germany,Comédia,2025

In [2]:
n_buget_zero = 0
for i in df[ 'budget' ]:
    if i == 0:
        n_buget_zero += 1
    else:
        pass

n_buget_zero
#sobra uns 10k filmes

66840

In [3]:
n_revenue_zero = 0
for i in df[ 'revenue' ]:
    if i == 0:
        n_revenue_zero += 1
    else:
        pass

n_revenue_zero

67503

In [4]:
df[ 'production_country' ].isna().sum()

np.int64(8976)

In [5]:
df[ 'genres' ].isna().sum()

np.int64(5851)

In [6]:
df = df[ df[ 'budget' ] != 0 ].reset_index( drop = True )

In [7]:
df

,title,release_date,vote_average,budget,vote_count,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,7065,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Priehrada,1950-08-23,2.000,195000,1,0,0,Czechoslovakia,Drama,1950
2,Crepúsculo dos Deuses,1950-08-10,8.281,1752000,2870,5000000,110,United States of America,Drama,1950
3,Julius Caesar,1950-03-08,5.800,15000,6,0,106,United States of America,"Drama, História",1950
4,A Malvada,1950-11-09,8.081,1400000,1663,8402553,138,United States of America,Drama,1950
...,...,...,...,...,...,...,...,...,...,...
9150,Sayap Sayap Patah 2: Olivia,2025-05-08,6.500,114,3,0,114,Indonesia,"Ação, Drama, Thriller",2025
9151,The Evolution of Horror Cinema Worldwide,2025-09-18,0.000,1000,0,1000,564,"Colombia, Spain","Documentário, Terror",2025
9152,Guerra 2,2025-08-13,5.776,47000000,58,3096145,173,India,"Ação, Aventura, Thriller",2025
9153,BLUNT,2025-09-06,0.000,6500,0,0,13,Australia,"Drama, Família, Comédia",2025
9154,Memórias de um Verão,2025-01-31,7.115,5000000,26,0,90,"Finland, United Kingdom, United States of America",Drama,2025

In [8]:
n_revenue_zero = 0
for i in df[ 'revenue' ]:
    if i == 0:
        n_revenue_zero += 1
    else:
        pass

n_revenue_zero

2630

In [9]:
df = df[ df[ 'revenue' ] != 0 ].reset_index( drop = True )

In [10]:
df

,title,release_date,vote_average,budget,vote_count,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,7065,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Crepúsculo dos Deuses,1950-08-10,8.281,1752000,2870,5000000,110,United States of America,Drama,1950
2,A Malvada,1950-11-09,8.081,1400000,1663,8402553,138,United States of America,Drama,1950
3,Coração Indômito,1950-11-06,6.222,300000,36,120000,111,United Kingdom,"Drama, Romance",1950
4,Rashomon,1950-08-26,8.041,250000,2464,117668,88,Japan,"Crime, Drama, Mistério",1950
...,...,...,...,...,...,...,...,...,...,...
6520,"Honey, Não!",2025-08-21,5.680,20000000,323,7445237,89,"United Kingdom, United States of America","Comédia, Crime",2025
6521,Depois da Caçada,2025-10-09,5.661,20000000,451,9426825,139,"United States of America, Italy",Drama,2025
6522,A Grande Viagem da Sua Vida,2025-09-17,6.300,45000000,320,22331708,110,"United States of America, Ireland","Romance, Fantasia, Drama",2025
6523,The Evolution of Horror Cinema Worldwide,2025-09-18,0.000,1000,0,1000,564,"Colombia, Spain","Documentário, Terror",2025
6524,Guerra 2,2025-08-13,5.776,47000000,58,3096145,173,India,"Ação, Aventura, Thriller",2025

In [11]:
df = df[ df[ 'vote_count' ] > 50 ]

In [12]:
df

,title,release_date,vote_average,budget,vote_count,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,7065,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Crepúsculo dos Deuses,1950-08-10,8.281,1752000,2870,5000000,110,United States of America,Drama,1950
2,A Malvada,1950-11-09,8.081,1400000,1663,8402553,138,United States of America,Drama,1950
4,Rashomon,1950-08-26,8.041,250000,2464,117668,88,Japan,"Crime, Drama, Mistério",1950
5,"Casa, Comida e Carinho",1950-08-31,6.600,2025000,56,3357000,108,United States of America,"Música, Romance",1950
...,...,...,...,...,...,...,...,...,...,...
6518,Sikandar,2025-03-29,4.955,23500000,66,24727058,133,India,"Ação, Drama",2025
6520,"Honey, Não!",2025-08-21,5.680,20000000,323,7445237,89,"United Kingdom, United States of America","Comédia, Crime",2025
6521,Depois da Caçada,2025-10-09,5.661,20000000,451,9426825,139,"United States of America, Italy",Drama,2025
6522,A Grande Viagem da Sua Vida,2025-09-17,6.300,45000000,320,22331708,110,"United States of America, Ireland","Romance, Fantasia, Drama",2025
6524,Guerra 2,2025-08-13,5.776,47000000,58,3096145,173,India,"Ação, Aventura, Thriller",2025

In [13]:
df[ 'production_country' ].isna().sum()

np.int64(2)

In [14]:
df.dropna()

df

,title,release_date,vote_average,budget,vote_count,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,7065,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Crepúsculo dos Deuses,1950-08-10,8.281,1752000,2870,5000000,110,United States of America,Drama,1950
2,A Malvada,1950-11-09,8.081,1400000,1663,8402553,138,United States of America,Drama,1950
4,Rashomon,1950-08-26,8.041,250000,2464,117668,88,Japan,"Crime, Drama, Mistério",1950
5,"Casa, Comida e Carinho",1950-08-31,6.600,2025000,56,3357000,108,United States of America,"Música, Romance",1950
...,...,...,...,...,...,...,...,...,...,...
6518,Sikandar,2025-03-29,4.955,23500000,66,24727058,133,India,"Ação, Drama",2025
6520,"Honey, Não!",2025-08-21,5.680,20000000,323,7445237,89,"United Kingdom, United States of America","Comédia, Crime",2025
6521,Depois da Caçada,2025-10-09,5.661,20000000,451,9426825,139,"United States of America, Italy",Drama,2025
6522,A Grande Viagem da Sua Vida,2025-09-17,6.300,45000000,320,22331708,110,"United States of America, Ireland","Romance, Fantasia, Drama",2025
6524,Guerra 2,2025-08-13,5.776,47000000,58,3096145,173,India,"Ação, Aventura, Thriller",2025

dataset pronto pra trabalhar

In [15]:
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")
df["release_year"] = df["release_year"].astype(str)

df = df.rename(columns={
    "title": "titulo",
    "release_date": "data_lancamento",
    "vote_average": "media_votos",
    "budget": "orcamento",
    "vote_count": "quantidade_votos",
    "revenue": "receita",
    "runtime": "duracao",
    "production_country": "pais_producao",
    "genres": "generos",
    "release_year": "ano_lancamento"
})

df.to_pickle('df_tmdb.pkl')

C:\Users\Gustavo\AppData\Local\Temp\ipykernel_21100\1141263478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")
C:\Users\Gustavo\AppData\Local\Temp\ipykernel_21100\1141263478.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["release_year"] = df["release_year"].astype(str)