In [6]:
import pandas as pd

df = pd.read_csv( 'filmes_tmdb.csv', sep = ',' )

df

,title,release_date,vote_average,budget,revenue,runtime,production_country,genres,release_year
0,Doctor X,1950-09-21,0.000,0,0,0,Philippines,"Comédia, Mistério, Terror",1950
1,Missão nos Balcãs,1950-12-06,6.000,0,0,90,United Kingdom,"Thriller, Ação",1950
2,Sarumba,1950-01-31,6.000,0,0,65,United States of America,"Drama, Música",1950
3,No Trace,1950-09-08,6.800,0,0,76,United Kingdom,"Crime, Drama",1950
4,Teatro Apolo,1950-10-30,6.300,0,0,105,NaN,Drama,1950
...,...,...,...,...,...,...,...,...,...
74968,யாவரும் வல்லவரே,2024-03-15,0.000,0,0,125,India,"Drama, Thriller",2024
74969,Ultraviolet,2024-11-14,0.000,0,0,24,"Belgium, Netherlands",Drama,2024
74970,Como Roubar um Banco,2024-06-04,6.700,0,0,88,United States of America,"Documentário, Crime",2024
74971,¿Es el enemigo? La película de Gila,2024-12-13,6.519,0,0,100,"Spain, Portugal","Comédia, Guerra",2024
74972,Perfect Boy Next Door,2024-02-28,0.000,0,0,10,NaN,NaN,2024

In [ ]:
n_buget_zero = 0
for i in df[ 'budget' ]:
    if i == 0:
        n_buget_zero += 1
    else:
        pass

n_buget_zero
#sobra uns 10k filmes

65900

In [12]:
n_revenue_zero = 0
for i in df[ 'revenue' ]:
    if i == 0:
        n_revenue_zero += 1
    else:
        pass

n_revenue_zero

66574

In [8]:
df[ 'production_country' ].isna().sum()

np.int64(8835)

In [10]:
df[ 'genres' ].isna().sum()

np.int64(5820)

In [13]:
df = df[ df[ 'budget' ] != 0 ].reset_index( drop = True )

In [14]:
df

,title,release_date,vote_average,budget,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Priehrada,1950-08-23,2.000,195000,0,0,Czechoslovakia,Drama,1950
2,Crepúsculo dos Deuses,1950-08-10,8.282,1752000,5000000,110,United States of America,Drama,1950
3,Julius Caesar,1950-03-08,5.800,15000,0,106,United States of America,"Drama, História",1950
4,A Malvada,1950-11-09,8.082,1400000,8402553,138,United States of America,Drama,1950
...,...,...,...,...,...,...,...,...,...
9068,Mergulho Noturno,2024-01-03,5.503,15000000,54785387,98,United States of America,"Terror, Mistério",2024
9069,Como Vender a Lua,2024-07-10,6.799,100000000,42260534,132,United States of America,"Romance, Comédia",2024
9070,A Menina e o Dragão,2024-04-11,7.700,25600000,6206231,98,"China, Spain","Animação, Família, Ação, Aventura, Fantasia",2024
9071,Looney Tunes - O Filme: O Dia Que a Terra Expl...,2024-08-01,7.581,15000000,15076954,91,United States of America,"Família, Comédia, Aventura, Animação, Ficção c...",2024
9072,Little Lillith,2024-12-13,6.000,2500,0,7,United States of America,"Terror, Ficção científica",2024

In [16]:
n_revenue_zero = 0
for i in df[ 'revenue' ]:
    if i == 0:
        n_revenue_zero += 1
    else:
        pass

n_revenue_zero

2605

In [17]:
df = df[ df[ 'revenue' ] != 0 ].reset_index( drop = True )

In [18]:
df

,title,release_date,vote_average,budget,revenue,runtime,production_country,genres,release_year
0,Cinderela,1950-02-22,7.044,2900000,263600000,74,United States of America,"Família, Fantasia, Animação, Romance",1950
1,Crepúsculo dos Deuses,1950-08-10,8.282,1752000,5000000,110,United States of America,Drama,1950
2,A Malvada,1950-11-09,8.082,1400000,8402553,138,United States of America,Drama,1950
3,Coração Indômito,1950-11-06,6.222,300000,120000,111,United Kingdom,"Drama, Romance",1950
4,Rashomon,1950-08-26,8.041,250000,117668,88,Japan,"Crime, Drama, Mistério",1950
...,...,...,...,...,...,...,...,...,...
6463,Back to Black,2024-04-11,6.656,30000000,51001975,122,"United Kingdom, United States of America","Música, História, Drama",2024
6464,Mergulho Noturno,2024-01-03,5.503,15000000,54785387,98,United States of America,"Terror, Mistério",2024
6465,Como Vender a Lua,2024-07-10,6.799,100000000,42260534,132,United States of America,"Romance, Comédia",2024
6466,A Menina e o Dragão,2024-04-11,7.700,25600000,6206231,98,"China, Spain","Animação, Família, Ação, Aventura, Fantasia",2024
6467,Looney Tunes - O Filme: O Dia Que a Terra Expl...,2024-08-01,7.581,15000000,15076954,91,United States of America,"Família, Comédia, Aventura, Animação, Ficção c...",2024